### ISSUE TITLE
Update python package on PIP

### ISSUE THREAD

**Issue by poseidonchan** [ScialdoneLab/CIARA_python#1]
Hi authors,

Thanks very much for your good algorithm to detect rare cells!
But it seems that your public pip version is not compatible with your repository. Besides, python package doesn't include those plotting functions in R packages which are crucial for people to recognize rare cells. It would be very nice if you can incorporate these functions into the python package.

Thanks again for your algorithms!

Yanshuo

**Comment by stkmrc** [comment]
Hi @poseidonchan,

Thank you for the hint! 
Indeed, the readme file on PyPI was an older version and I fixed it in the lastest version 1.0.4.

Regarding the plotting functions, we are working on implementing them in the python package at the moment. For now, the standard scanpy plotting can be used to e.g. visualize the location of the top markers in the UMAP as seen in the tutorial, but the same easy-to-use plotting functions from the R package will be introduced as well!

Glad that you like the algorithm!

Greetings from Munich, Germany
Marco

**Comment by poseidonchan** [comment]
Thanks!
